idf_component_register(
    SRCS
        "main.c"
        "audio_test.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        common
        display_driver
        ui_manager_lvgl
        sd_card_manager
        lvgl_sd_fs
        lvgl_image_handler
        performance_monitor
        wifi_manager
        app_gui
        sensor_manager
        cloud_manager
        firebase_auth
        config_manager
        provisioning_manager
        app_network_coordinator
        button_manager
        app_reset_coordinator

    PRIV_REQUIRES
        nvs_flash
        esp_netif
        esp_event
        esp_driver_i2s
)
