#pragma once

typedef enum {
    CLOUD_MANAGER_STATE_UNINITIALIZED = 0,
    CLOUD_MANAGER_STATE_INITIALIZED,
    CLOUD_MANAGER_STATE_WAITING_FOR_NETWORK,
    CLOUD_MANAGER_STATE_WAITING_FOR_DATA,
    CLOUD_MANAGER_STATE_UPLOADING,
    CLOUD_MANAGER_STATE_ONLINE,
    CLOUD_MANAGER_STATE_RETRY_WAIT,
    CLOUD_MANAGER_STATE_AUTH_ERROR,
    CLOUD_MANAGER_STATE_ERROR,
} cloud_manager_state_t;

typedef struct {
    cloud_manager_state_t state;
} cloud_manager_status_t;
