#!/usr/bin/env python3
"""Generate the LVGL font used for Vietnamese and English Xiaozhi text.

The generated source intentionally includes only Latin, Vietnamese, common
punctuation, and an ellipsis. Chinese is provided separately by LVGL's bundled
Source Han Sans SC fallback font. Noto Sans SC is licensed under the SIL Open
Font License 1.1; verify the local font metadata before regenerating.
"""

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


FONT_NAME = "app_gui_xiaozhi_latin_12"
FONT_SIZE_PX = 12
BITS_PER_PIXEL = 4


def selected_codepoints():
    """Return the bounded Latin/Vietnamese transcript repertoire."""
    codepoints = set(range(0x20, 0x7F))
    codepoints.update(range(0xA0, 0x100))
    codepoints.update(
        {
            0x0102, 0x0103, 0x0110, 0x0111, 0x0128, 0x0129,
            0x0168, 0x0169, 0x01A0, 0x01A1, 0x01AF, 0x01B0,
            0x20AB, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026,
        }
    )
    codepoints.update(range(0x1EA0, 0x1EFA))
    return sorted(codepoints)


def pack_bitmap(image):
    """Pack an 8-bit Pillow bitmap into LVGL's 4-bit, row-major format."""
    packed = []
    pixels = list(image.get_flattened_data())
    for index in range(0, len(pixels), 2):
        high = (pixels[index] * 15 + 127) // 255
        low = 0
        if index + 1 < len(pixels):
            low = (pixels[index + 1] * 15 + 127) // 255
        packed.append((high << 4) | low)
    return packed


def render_glyph(font, codepoint):
    """Return LVGL metrics and a clipped glyph bitmap for one Unicode point."""
    character = chr(codepoint)
    left, top, right, bottom = font.getbbox(character)
    baseline_left, baseline_top, baseline_right, baseline_bottom = (
        font.getbbox(character, anchor="ls")
    )
    del baseline_left, baseline_top, baseline_right

    width = max(right - left, 0)
    height = max(bottom - top, 0)
    if width == 0 or height == 0:
        return {
            "adv_w": round(font.getlength(character) * 16),
            "box_w": 0,
            "box_h": 0,
            "ofs_x": 0,
            "ofs_y": 0,
            "bitmap": [],
        }

    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=255)
    return {
        "adv_w": round(font.getlength(character) * 16),
        "box_w": width,
        "box_h": height,
        "ofs_x": left,
        "ofs_y": -baseline_bottom,
        "bitmap": pack_bitmap(image),
    }


def chunks(values, size):
    for index in range(0, len(values), size):
        yield values[index:index + size]


def emit_font(output_path, font_path):
    font = ImageFont.truetype(str(font_path), FONT_SIZE_PX)
    codepoints = []
    glyphs = []
    for codepoint in selected_codepoints():
        codepoints.append(codepoint)
        glyphs.append(render_glyph(font, codepoint))

    bitmap = []
    bitmap_indices = []
    for glyph in glyphs:
        bitmap_indices.append(len(bitmap))
        bitmap.extend(glyph["bitmap"])

    ascent, descent = font.getmetrics()
    offsets = [codepoint - codepoints[0] for codepoint in codepoints]
    lines = [
        "/*",
        " * Generated by generate_xiaozhi_latin_font.py from Noto Sans SC.",
        " * Noto Sans SC is licensed under the SIL Open Font License 1.1.",
        " * Font size: 12 px, 4 bpp. Do not edit this generated file manually.",
        " */",
        "#include \"app_gui_xiaozhi_latin_12.h\"",
        "",
        "static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {",
    ]
    for chunk in chunks(bitmap, 12):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend(["};", "", "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {"])
    lines.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},")
    for glyph, bitmap_index in zip(glyphs, bitmap_indices):
        lines.append(
            "    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},"
            % (bitmap_index, glyph["adv_w"], glyph["box_w"], glyph["box_h"], glyph["ofs_x"], glyph["ofs_y"])
        )
    lines.extend(["};", "", "static const uint16_t unicode_list[] = {"])
    for chunk in chunks(offsets, 12):
        lines.append("    " + ", ".join(str(value) for value in chunk) + ",")
    lines.extend([
        "};",
        "",
        "static const lv_font_fmt_txt_cmap_t cmaps[] = {",
        "    {.range_start = %d, .range_length = %d, .glyph_id_start = 1," % (codepoints[0], codepoints[-1] - codepoints[0] + 1),
        "     .unicode_list = unicode_list, .glyph_id_ofs_list = NULL, .list_length = %d," % len(codepoints),
        "     .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY},",
        "};",
        "",
        "static const lv_font_fmt_txt_dsc_t font_dsc = {",
        "    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps,",
        "    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1, .bpp = 4,",
        "    .kern_classes = 0, .bitmap_format = LV_FONT_FMT_TXT_PLAIN, .stride = 0,",
        "};",
        "",
        "const lv_font_t %s = {" % FONT_NAME,
        "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,",
        "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
        "    .line_height = %d, .base_line = %d," % (ascent + descent, descent),
        "    .subpx = LV_FONT_SUBPX_NONE, .underline_position = -2,",
        "    .underline_thickness = 1, .dsc = &font_dsc, .fallback = NULL,",
        "};",
        "",
    ])
    output_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    emit_font(args.output, args.font)


if __name__ == "__main__":
    main()
